# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 04:27
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=dashboard.models.image_upload_path)),
                ('description', models.CharField(max_length=225)),
                ('stock', models.IntegerField()),
                ('title', models.CharField(max_length=225)),
                ('featured', models.CharField(max_length=200)),
                ('active', models.CharField(max_length=200)),
                ('cod', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(to='dashboard.Product'),
        ),
    ]
