# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 05:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile', models.CharField(help_text=b'10 digit mobile number', max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.IntegerField(help_text=b'6 digit valid Postel code', validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
                ('status', models.CharField(choices=[(b'initiated', b'initiated'), (b'processing', b'processing'), (b'dispatched', b'dispatched')], default=b'initiated', max_length=20)),
                ('payment_option', models.CharField(choices=[(b'cod', b'cash on delivery')], max_length=10)),
                ('items', models.TextField()),
                ('total_price', models.FloatField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
